### ISSUE TITLE
Doesn't get installed due to old dependencies

### ISSUE THREAD

**Issue by karoria** [cncjs/cncjs-pendant-boilerplate#2]
I am installing it on Raspberry Pi 4 but no success due to old and unmanaged dependencies, this happens with keyboard pendant too as it is based on this pendant. Kindly update or guide for a workaround.

**Comment by MitchBradley** [comment]
I tried updating it awhile ago and got it to compile, but I got bogged down in other problems.  That pendant is sort of a mess; it depends on several factors that are hard to control.  I gave up because I have too many other more important things to do.

**Comment by karoria** [comment]
@MitchBradley 
Thanks for your efforts. I wonder why shopfloor tablet doesn't have such issues and also it has very different installation process. BTW, can we use keyboard pendant with shopfloor tablet by moving that file somewhere in its file system? I want to assign almost all functions to that tiny keyboard (including feed and spindle overrides if possible). It is super useful and handy.

**Comment by nsfilho** [comment]
I'll try to help on that.
